BurnsWilcoxCLP.Web/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BurnsWilcoxCLP.Web.Controllers
{
    public class LocationsController : Controller
    {
        public ActionResult GetPartialLocations(string policyNumber)
        {
            return PartialView();
        }
    }
}

BurnsWilcoxCLP.Web/Views/Locations/GetPartialLocations.cshtml
@model BurnsWilcoxCLP.Models.LocationEntity

@using(Html.BeginForm("GetPartialLocations", "Locations", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    
  
        <div class="row">
            <div class="col-sm-2">
                <div class="form-group  ">
                    <label>Location</label>
                    @Html.DropDownListFor(m => m.LocationId, new SelectList("Id", "Name"), "--Select--", new { @class = "form-control", tabindex = "1", required = "required" })
                    @Html.ValidationMessageFor(m => m.LocationId)
                </div>
            </div>
        </div>
        <div class="row ">
            <div class="col-lg-6 col-md-6">
                <div class="form-group">
                    <span>Location Description</span>
                    @Html.TextBoxFor(m => m.LocationDescription, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.LocationDescription)
                </div>
                <div class="form-group">
                    <span>Address Line 1*</span>
                    @Html.TextBoxFor(m => m.AddessL1, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.AddessL1)
                </div>
                <div class="form-group">
                    <span>Address Line 2</span>
                    @Html.TextBoxFor(m => m.AddessL2, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.AddessL2)
                </div>
                <div class="form-group">
                    <span>Postal Code</span>
                    @Html.TextBoxFor(m => m.PostalCode, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.PostalCode)
                </div>

            </div>
            <div class="col-lg-6 col-md-6">
                <div class="form-group">
                    <span>City*</span>
                    @Html.TextBoxFor(m=>m.City, new { @class="form-control" })
                    @Html.ValidationMessageFor(m=>m.City)
                </div>
                <div class="form-group">
                    <span>State*</span>
                    @Html.TextBoxFor(m=>m.State, new { @class="form-control" })
                    @Html.ValidationMessageFor(m=>m.State)
                </div>
                <div class="form-group">
                    <span>Country*</span>
                    @Html.TextBoxFor(m=>m.Country, new { @class="form-control" })
                    @Html.ValidationMessageFor(m=>m.Country)
                </div>
                <div class="form-group">
                    <span>TownCode</span>
                    @Html.TextBoxFor(m=>m.TownCode, new { @class="form-control" })
                    @Html.ValidationMessageFor(m => m.TownCode)
                </div>
            </div>

        </div>
        <div class="form-group">
            @Html.CheckBoxFor(m=>m.InCity, new { @class = "btn btn-success" }) InCity Limit
            @Html.ValidationMessageFor(m => m.InCity)
        </div>
   
}