BurnsWilcoxCLP.Web/Controllers/UserRightsController.cs
using BurnsWilcoxCLP.API.API;
using BurnsWilcoxCLP.Models;
using Kendo.Mvc.UI;
using System;
using System.Web.Script.Serialization;
using System.Collections.Generic;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using System.Data;


namespace BurnsWilcoxCLP.Web.Controllers
{
    public class UserRightsController : BaseAdminController
    {
        // GET: UserRights

        private readonly UserAPIController _userapicontroller;
        public UserRightsController()
        {
            _userapicontroller = new UserAPIController();
        } 
      //  [Route("UserRights")]
        public ActionResult Index()
        {
            UserTypeEntity model = new UserTypeEntity();
            var userTypeList = _userapicontroller.GetUserTypelist();
            ViewBag.UserTypeId = new SelectList(userTypeList, "UserTypeId", "Name");
            return View(model);
        }
        public ActionResult UserAccesRight(short userTypeId)
        {
            var userTypeList = _userapicontroller.GetUserTypelist();
            ViewBag.UserTypeId = new SelectList(userTypeList, "UserTypeId", "Name",userTypeId);

            var userList = _userapicontroller.GetUserTypeMenuSearchlist(userTypeId);
            
            return Json(new{userList},JsonRequestBehavior.AllowGet);
            
        }

        public ActionResult ReadUserTypeAction(DataSourceRequest request, short userTypeId)
        {
            var userList = _userapicontroller.GetUserTypeMenuSearchlist(userTypeId);
            return Json(userList.ToDataSourceResult(request));
        }

        public string Save(List<UserTypeMenuSearch> model)
        {
                try
                {
                    var serializer = new JavaScriptSerializer();

                    var userTypeMenuSearchList = model;

                    #region DataTable
                    DataTable dtUserTypeMenus = new DataTable("UserTypeMenusTable");
                    dtUserTypeMenus.Columns.Add("UserTypeMenuId");
                    dtUserTypeMenus.Columns.Add("MenuId");
                    dtUserTypeMenus.Columns.Add("UserTypeId");
                    dtUserTypeMenus.Columns.Add("IsView");
                    dtUserTypeMenus.Columns.Add("IsAdd");
                    dtUserTypeMenus.Columns.Add("IsDelete");
                    dtUserTypeMenus.Columns.Add("IsEdit");
                    #endregion

                    foreach (UserTypeMenuSearch objUserTypeMenuSearch in userTypeMenuSearchList)
                    {
                        DataRow dtrow = dtUserTypeMenus.NewRow();
                        dtrow["UserTypeMenuId"] = objUserTypeMenuSearch.UserTypeMenuId;
                        dtrow["MenuId"] = objUserTypeMenuSearch.MenuId;
                        dtrow["UserTypeId"] = objUserTypeMenuSearch.UserTypeId;
                        dtrow["IsView"] = objUserTypeMenuSearch.IsView;
                        dtrow["IsAdd"] = objUserTypeMenuSearch.IsAdd;
                        dtrow["IsDelete"] = objUserTypeMenuSearch.IsDelete;
                        dtrow["IsEdit"] = objUserTypeMenuSearch.IsEdit;
                        dtUserTypeMenus.Rows.Add(dtrow);
                    }

                    int count =  _userapicontroller.SaveUserTypeActions(dtUserTypeMenus);
                    if (count > 0)
                    {
                        this.SuccessNotification("Right Added");
                    }

               return string.Empty;
                }
                catch (Exception ex)
                {
                    return ex.ToString();
                }
        }

    }
}

BurnsWilcoxCLP.Web/Views/UserRights/Index.cshtml
@model BurnsWilcoxCLP.Models.UserTypeEntity
@{
    ViewBag.Title = "Index";
}
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<link href="~/Content/css/jquery.dataTables.min.css" rel="stylesheet" /> 
<div class="content">
    <h4>Manage Access Rights</h4>
    @Html.Partial("_Notifications")
           <div class="panel panel-default">
               <div class="panel-body">
                   <label class="label">User Type</label>
                   
                   <div class="col-sm-6">

                       @Html.DropDownListFor(m => m.UserTypeId, null, "--Select userType--", htmlAttributes: new { @class = "select col-sm-2" })
                       @Html.ValidationMessageFor(m => m.UserTypeId, "", new { @style = "color:red" })
                   </div>

               </div>
              
                    <div>
                        <div class="panel-body table-responsive" id="showGrid" hidden>
                            <table class="table panel"  id="tbluserMenuAccess">    </table>


                            <button class="btn btn-orange mt-5 mr-10 pull-right" id="save" type="button">Save</button>
                        </div>
                    </div>
             

               </div>
               </div>
<script type="text/javascript">
    $('#UserTypeId').change(function () {
        debugger
        var userTypeId = $('#UserTypeId').val();
        $("#showGrid").show();
        if (userTypeId == ""  || userTypeId == undefined)
        {
            $("#showGrid").hide();
        }
        
        BindMenuAccess(userTypeId);
        debugger
        //$("#tbluserMenuAccess").removeClass("dataTable");
    });

    function PrepareDataToSave() {
        var modelList = [];
        var objmodel = new Object();
        $("#tbluserMenuAccess tbody tr").each(function (index, item) {

            objmodel = new Object();

            objmodel["UserTypeMenuId"] = $(item).find("input[type=hidden]").attr("data-usertypemenuid");
            objmodel["MenuId"] = $(item).find("input[type=hidden]").attr("data-menuid");
            objmodel["UserTypeId"] = $('#UserTypeId').val();
            objmodel["IsAdd"] = $(item).find('input[data-menu="IsAdd"]').prop("checked");
            objmodel["IsDelete"] = $(item).find('input[data-menu="IsDelete"]').prop("checked");
            objmodel["IsView"] = $(item).find('input[data-menu="IsView"]').prop("checked");
            objmodel["IsEdit"] = $(item).find('input[data-menu="IsEdit"]').prop("checked");

            modelList.push(objmodel);
        });

        return modelList;
    }

    function BindMenuAccess(userTypeId) {
        debugger
        var TeamData = [];
        $.ajax({
            url: '@Url.Action("UserAccesRight", "UserRights")',
            data: { 'userTypeId': userTypeId },
            dataType: "json",
            async: true,
            success: function (data) {
                TeamData = data.userList;
                if ($.fn.DataTable.isDataTable("#tbluserMenuAccess")) {
                    $('#tbluserMenuAccess').DataTable().destroy();
                }
                $('#tbluserMenuAccess').DataTable({
                    data: TeamData,
                    "bDestroy": true,
                    "dom": '<"top"><><"bottom"<"clear">>',
                    "aLengthMenu": [10, 20, 50, 100, 200],
                    "pageLength": 10,
                    "orderSequence": ["desc", "asc"],
                    "bAutoWidth": false,
                    "columns": [
                        { "data": "MenuId", "visible": false, },
                { "data": "UserTypeMenuId", "visible": false, },
                { "data": "UserTypeId", "visible": false, },

                        { "title": "MenuName", "data": "MenuName", "orderable": false, "order": [] },
                        {
                            "title": "Add", "data": "IsAdd",
                            "sTitle": "Add</br><input type='checkbox' class=checker id='chkHeaderAdd' onclick='checkAllAdd(this)'/>",
                            
                            "sorting": "false",
                            "orderable": false, "order": [],
                            "render": function (data, type, row) {
                                var hidden = '<input type="hidden" data-usertypemenuid=' + row.UserTypeMenuId + '  data-menuid=' + row.MenuId + '>';
                                if (row.IsAdd == true) {
                                    return hidden + '<input type="checkbox" data-menu="IsAdd" class="editor-active checker"  checked onclick="SetHeaderCheckboxStatus()">';
                                }
                                else {
                                    return hidden + '<input type="checkbox"  data-menu="IsAdd" class="editor-active checker"  onclick="SetHeaderCheckboxStatus()">';
                                }
                            }
                        },


                        {
                            "title": "Delete", "data": "IsDelete",
                            "sTitle": "Delete</br><input type='checkbox' class=checker id='chkHeaderDelete' onclick='checkAllDelete(this)'/>",
                            "sClass": "action",
                            "sorting": "false",
                            "orderable": false, "order": [],
                            "render": function (data, type, row) {
                                if (row.IsDelete == true) {
                                    return '<input type="checkbox" data-menu="IsDelete"  class="editor-active checker" checked onclick="SetHeaderCheckboxStatus()">';
                                }
                                else {
                                    return '<input type="checkbox" data-menu="IsDelete"  class="editor-active checker" onclick="SetHeaderCheckboxStatus()">';
                                }
                            }
                        },
                         {
                             "title": "View", "data": "IsView",
                             "sTitle": "View</br><input type='checkbox' class=checker id='chkHeaderView'  onclick='checkAllView(this)'/>",
                             "sClass": "action",
                             "sorting": "false",
                             "orderable": false, "order": [],
                             "render": function (data, type, row) {
                                 if (row.IsView == true) {
                                     return '<input type="checkbox"  data-menu="IsView" class="editor-active checker" checked onclick="SetHeaderCheckboxStatus()">';
                                 }
                                 else {
                                     return '<input type="checkbox" data-menu="IsView" class="editor-active checker" onclick="SetHeaderCheckboxStatus()">';
                                 }
                             }
                         },
                    {

                        "title": "Edit", "data": "IsEdit",
                        "sTitle": "Edit</br><input type='checkbox' class=checker id='chkHeaderEdit' onclick='checkAllEdit(this)'/>",
                        "sClass": "action",
                        "sorting": "false",
                        "orderable": false, "order": [],
                        "render": function (data, type, row) {
                            if (row.IsEdit == true) {
                                return '<input type="checkbox" data-menu="IsEdit"  class="editor-active checker" checker checked onclick="SetHeaderCheckboxStatus()">';
                            }
                            else {
                                return '<input type="checkbox" data-menu="IsEdit" class="editor-active checker" onclick="SetHeaderCheckboxStatus()">';
                            }
                        }
                    },
                    ], 
                    "initComplete": function () {
                        var dataTable = $('#tbluserMenuAccess').DataTable();

                    },
                    "fnDrawCallback": function () {
                        SetHeaderCheckboxStatus();
                    }
                });
            }
        });
    }


    $("#save").click(function () {
        var modelList = PrepareDataToSave();
        $.ajax({
            url: '@Url.Action("Save", "UserRights")',
            data: JSON.stringify({ "model": modelList }),
            contentType: 'application/json; charset=utf-8',
            type: 'POST',
            dataType: 'json',

            success: function (data) {
                alert(data);
            }
        });
    });
    function checkAllAdd(ele) {
        if (ele.id == "chkHeaderAdd")
        {
            debugger
            if (ele.checked == false) {
                $('#tbluserMenuAccess tbody input[data-menu="IsAdd"]').prop("checked", false)
            }
            else {
                $('#tbluserMenuAccess tbody input[data-menu="IsAdd"]').prop("checked", true)
            }
        }
    }

     

    function SetHeaderCheckboxStatus()
    {
        var length = $('#tbluserMenuAccess tbody input[data-menu="IsAdd"]').length
        var totallength = $('#tbluserMenuAccess tbody input[data-menu="IsAdd"]:checked').length
        $("#tbluserMenuAccess").find("input[id=chkHeaderAdd]").prop("checked", length == totallength);

        var length = $('#tbluserMenuAccess tbody input[data-menu="IsDelete"]').length
        var totallength = $('#tbluserMenuAccess tbody input[data-menu="IsDelete"]:checked').length
        $("#tbluserMenuAccess").find("input[id=chkHeaderDelete]").prop("checked", length == totallength);

        var length = $('#tbluserMenuAccess tbody input[data-menu="IsView"]').length
        var totallength = $('#tbluserMenuAccess tbody input[data-menu="IsView"]:checked').length
        $("#tbluserMenuAccess").find("input[id=chkHeaderView]").prop("checked", length == totallength);

        var length = $('#tbluserMenuAccess tbody input[data-menu="IsEdit"]').length
        var totallength = $('#tbluserMenuAccess tbody input[data-menu="IsEdit"]:checked').length
        $("#tbluserMenuAccess").find("input[id=chkHeaderEdit]").prop("checked", length == totallength);
    }
    
    function checkAllDelete(ele) {
        if (ele.id == "chkHeaderDelete") {
            debugger
            if (ele.checked == false) {
                $('#tbluserMenuAccess tbody input[data-menu="IsDelete"]').prop("checked", false)
            }
            else {
                $('#tbluserMenuAccess tbody input[data-menu="IsDelete"]').prop("checked", true)
            }
        }
    }


    function checkAllView(ele) {
        if (ele.id == "chkHeaderView") {
            debugger
            if (ele.checked == false) {
                $('#tbluserMenuAccess tbody input[data-menu="IsView"]').prop("checked", false)
            }
            else {
                $('#tbluserMenuAccess tbody input[data-menu="IsView"]').prop("checked", true)
            }
        }
    }
    function checkAllEdit(ele) {
        if (ele.id == "chkHeaderEdit") {
            debugger
            if (ele.checked == false) {
                $('#tbluserMenuAccess tbody input[data-menu="IsEdit"]').prop("checked", false)
            }
            else {
                $('#tbluserMenuAccess tbody input[data-menu="IsEdit"]').prop("checked", true)
            }
        }
    }


</script>

BurnsWilcoxCLP.Web/Views/UserRights/_UserTypeMenuAssignment.cshtml
@using BurnsWilcoxCLP.Web.Helper
@using BurnsWilcoxCLP.Models
@using Kendo.Mvc.UI
<style>
    .k-edit-form-container {
        width: 615px !important;
    }
</style>

<div class="k-edit-form-container">
    @(Html.Kendo().Grid<UserTypeMenuSearch>()
          .Name("gvRoleMenus")
          .Columns(columns =>
          {
              columns.Bound(x => x.MenuName).Title("Menus");
              columns.Bound(x => x.IsView).Title("View")
                  .ClientTemplate(@"<input type='checkbox' class='chkView'  value='#= IsView #' #= IsView ? checked='checked':'' #/>")
                  .HtmlAttributes(WebHelper.StatusColumnStyle)
                  .HeaderTemplate(@"View <br/><input type='checkbox' id='chkHeaderView'  onclick='checkAllView(this)'/>")
                  .HeaderHtmlAttributes(WebHelper.StatusColumnStyle);
              columns.Bound(x => x.IsEdit).Title("Edit")
                  .ClientTemplate(@"<input type='checkbox' class= 'chkEdit'  value='#= IsEdit #' #= IsEdit ? checked='checked':'' #/>")
                  .HtmlAttributes(WebHelper.StatusColumnStyle)
                  .HeaderTemplate(@"Edit <br/><input type='checkbox' id='chkHeaderEdit' onclick='checkAllEdit(this)'></input>")
                  .HeaderHtmlAttributes(WebHelper.StatusColumnStyle);
              columns.Bound(x => x.IsAdd).Title("Add")
                  .ClientTemplate(@"<input type='checkbox' class='chkAdd'  value='#= IsAdd #' #= IsAdd ? checked='checked':'' #/>")
                  .HtmlAttributes(WebHelper.StatusColumnStyle)
                  .HeaderTemplate(@"Add <br/><input  type='checkbox' id='chkHeaderAdd' onclick='checkAllAdd(this)'></input>")
                  .HeaderHtmlAttributes(WebHelper.StatusColumnStyle);
              columns.Bound(x => x.IsDelete).Title("Delete")
                  .ClientTemplate(@"<input type='checkbox' class= 'chkDelete'  value='#= IsDelete #' #= IsDelete ? checked='checked':'' #/>")
                  .HtmlAttributes(WebHelper.StatusColumnStyle)
                  .HeaderTemplate(@"Delete <br/><input type='checkbox' id='chkHeaderDelete' onclick='checkAllDelete(this)'></input>")
                  .HeaderHtmlAttributes(WebHelper.StatusColumnStyle);

          })
          .Editable(editable => editable.Mode(GridEditMode.InCell))
          .Pageable(x => x.Enabled(false))
          .NoRecords()
          .Events(grid => grid.DataBound("dataBound"))
          .DataSource(dataSource => dataSource
              .Ajax()
              .ServerOperation(false)
              .Batch(true)
              .Events(events => events.RequestEnd("onGridDataSourceRequestEnd"))
              .Model(model =>
              {
                  model.Id(product => product.UserTypeMenuId);
                  model.Field(product => product.MenuName).Editable(false);
              })
                     .Read(read => read.Action("ReadUserTypeAction", "UserRights").Data("additionalInfo"))
          ))
    <div class="k-edit-buttons k-state-default">
        <a class="k-button btn-orange k-button k-button-icontext" href="#" title="Save" onclick="Save()">Save</a>
        <a class="k-button btn-orange k-button k-button-icontext" href="#" title="Reset" onclick="Reset()">Reset</a>
        <a class="k-button btn-orange k-button k-button-icontext" href="#" title="Cancel" onclick="ClosePopup()">Cancel</a>
    </div>
</div>

<script>
    $(function () {
        $('#gvRoleMenus').on('click', '.chkView', function () {
            var checked = $(this).is(':checked');
            var grid = $('#gvRoleMenus').data().kendoGrid;
            var dataItem = grid.dataItem($(this).closest('tr'));
            dataItem.set('IsView', checked);
            CheckAllView();
        });

        $('#gvRoleMenus').on('click', '.chkEdit', function () {
            var checked = $(this).is(':checked');
            var grid = $('#gvRoleMenus').data().kendoGrid;
            var dataItem = grid.dataItem($(this).closest('tr'));
            dataItem.set('IsEdit', checked);
            CheckAllEdit();
        });

        $('#gvRoleMenus').on('click', '.chkAdd', function () {
            var checked = $(this).is(':checked');
            var grid = $('#gvRoleMenus').data().kendoGrid;
            var dataItem = grid.dataItem($(this).closest('tr'));
            dataItem.set('IsAdd', checked);
            CheckAllAdd();
        });

        $('#gvRoleMenus').on('click', '.chkDelete', function () {
            var checked = $(this).is(':checked');
            var grid = $('#gvRoleMenus').data().kendoGrid;
            var dataItem = grid.dataItem($(this).closest('tr'));
            dataItem.set('IsDelete', checked);
            CheckAllDelete();
        });
    });

    function checkAllView(ele) {
        var state = $(ele).is(':checked');
        var grid = $('#gvRoleMenus').data().kendoGrid;
        $.each(grid.dataSource._data, function () {
            if (this['IsView'] !== state)
                this.dirty = true;
            this['IsView'] = state;
        });
        grid.refresh();
    }

    function checkAllEdit(ele) {
        var state = $(ele).is(':checked');
        var grid = $('#gvRoleMenus').data().kendoGrid;
        $.each(grid.dataSource._data, function () {
            if (this['IsEdit'] !== state)
                this.dirty = true;
            this['IsEdit'] = state;
        });
        grid.refresh();
    }

    function checkAllAdd(ele) {
        var state = $(ele).is(':checked');
        var grid = $('#gvRoleMenus').data().kendoGrid;
        $.each(grid.dataSource._data, function () {
            if (this['IsAdd'] !== state)
                this.dirty = true;
            this['IsAdd'] = state;
        });
        grid.refresh();
    }

    function checkAllDelete(ele) {
        var state = $(ele).is(':checked');
        var grid = $('#gvRoleMenus').data().kendoGrid;
        $.each(grid.dataSource._data, function () {
            if (this['IsDelete'] !== state)
                this.dirty = true;
            this['IsDelete'] = state;
        });
        grid.refresh();
    }

    function ClosePopup() {
        debugger
        closeKendoWindow("window");
    }

    function Save() {

        debugger
        var url = '@Url.Action("Save", "UserRights")';
        var gridData = $("#gvRoleMenus").data("kendoGrid").dataSource.data();
        var paramValue = kendo.stringify(gridData);
        callwebservice(url, "model=" + paramValue, function (data) {
            if (data == null || data === '') {
                ClosePopup();
            } else {
                showMessageOnly(data);
            }
        }, true, datatypeEnum.text);

    }

 
    </script>